pipeline:
  clone:
    image: plugins/git
    tags: true
  build:
    image: maven:3.3.9-jdk-8
    commands:
      - curl --fail --create-dirs -o $HOME/.gradle/init.d/mirror.gradle https://maven.johni0702.de/config/gradle
      - curl --fail --create-dirs -o $HOME/.m2/settings.xml https://maven.johni0702.de/config/maven
      - JAVA_OPTS=-Xmx1516M ./gradlew setupDecompWorkspace
      - ./gradlew :build
  archive:
    image: plugins/s3
    acl: public-read
    region: "us-east-1"
    bucket: "replaymod"
    path_style: true
    source: build/libs/*
    strip_prefix: build/libs/
    target: /
