pipeline:
  clone:
    image: plugins/git
    tags: true
    recursive: true
  build:
    image: maven:3.3.9-jdk-8
    commands:
      - curl --fail --create-dirs -o $HOME/.gradle/init.d/mirror.gradle https://maven.johni0702.de/config/gradle
      - git config --global user.email "replaymod@drone" && git config --global user.name "Drone"
      - SIGNED_JAR=$(! git describe --exact 2>&1 > /dev/null; echo $?) REPRODUCIBLE_BUILD=1 ./gradlew $(bash -c "echo :{1.8,1.8.9,1.9.4,1.10.2,1.11,1.11.2,1.12,1.12.1,1.12.2}:reobfJar") --parallel
      - mkdir -p build/libs && mv versions/*/build/libs/* build/libs/
  archive:
    image: plugins/s3
    acl: public-read
    region: "us-east-1"
    bucket: "replaymod"
    path_style: true
    source: build/libs/*
    strip_prefix: build/libs/
    target: /
